### ISSUE TITLE
[UI/UX] Create Logo (?)

### ISSUE THREAD

**Issue by microfauna** [nativesintech/native-owned-businesses#19]
Comment logo ideas here ~

**Comment by arecvlohe** [comment]
Possibly a derivative of the Natives in Tech logo

**Comment by elibrumbaugh** [comment]
I can help with this. What did you have in mind?

**Comment by arecvlohe** [comment]
I think we are going to continue the NiT branding for this site as well

**Comment by arecvlohe** [comment]
Going with black/white NiT logo for now :)
