### ISSUE TITLE
[BE] Get tag search working

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/native-owned-businesses#23]
## Background

Allow user to add predefined list of tags, i.e. food, clothing.

## Acceptance Criteria

- Get DB query to add predefined tags
- Respect auth permissions

**Comment by jayciro** [comment]
Something to think about... 

I like how Google My Business breaks down their "attributes" into 2 types: 

Factual attributes, like Black-owned, outdoor seating, or women-led
Subjective attributes, like whether your business is popular with locals

"You can directly edit certain factual attributes. However, subjective attributes rely on the opinions of Google customers who’ve visited your business.  "

https://support.google.com/business/answer/9049526
