### ISSUE TITLE
[Devops] Create deployment process

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/native-owned-businesses#40]
## Background

Create deployment process, possibly CI/CD.

**Comment by microfauna** [comment]
This is done! I moved our deploy from our server to Netlify. Should I include the netlify badge to close the ticket out? (does a netlify badge have any privacy / security implications?)

**Comment by arecvlohe** [comment]
> This is done! I moved our deploy from our server to Netlify. Should I include the netlify badge to close the ticket out? (does a netlify badge have any privacy / security implications?)

The badge has less privacy implications if we just save it and serve it up locally as opposed to using the URL 🤷‍♂️
